default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: myApp
  host: railsondocker-postgres-1
  port: 5432
  username: postgres
  password: 103930

test:
  <<: *default
  database: myApp
  host: railsondocker-postgres-1
  port: 5432
  username: postgres
  password: 103930